### ISSUE TITLE
Converted files #include path option

### ISSUE THREAD

**Issue by genius257** [genius257/au3class#4]
Currently converted code needs `AutoItObject_Internal.au3` to run.
An include in the top is inserted, but it's just a static string always at the same directory as the script (unless globally available).
An option to set this (via global variable or via the function calls as an optional parameter) would be great

**Comment by ghost** [comment]
Hi there,
not sure if you have already an idea about this. I had this problem and solved it with a custom directive `#pragma class(AIO_Internal, @ScriptDir & "\includes\AutoItObject_Internal.au3")`.

With the way you built `Class.au3`, it was really easy to extend it.

Thanks for your work and have a nice day.

**Comment by genius257** [comment]
Hi @steven-kleist 😄 
Thanks for your suggestion, it's a clever idea 😃 
This issue will be solved in my next version, that no longer will use AutoItObject_Internal.
It will instead generate code for IDispatch code specifically matching methods and properties.
This should help with speed a lot, when internal property indices are known, instead of searching all of the properties each time 😄

**Comment by genius257** [comment]
This issue is now solved, due to the AutoItObject_Internal dependency being removed
